install.packages("impute")
install.packages("pcaMethods")
install.packages("globaltest")
install.packages("GlobalAncova")
install.packages("Rgraphviz")
install.packages("preprocessCore")
install.packages("genefilter")
install.packages("SSPA")
install.packages("sva")
install.packages("limma")
install.packages("KEGGgraph")
install.packages("siggenes")
install.packages("BiocParallel")
install.packages("MSnbase")
install.packages("multtest")
install.packages("RBGL")
install.packages("edgeR")
install.packages("fgsea")
install.packages("httr")
install.packages("qs")

install.packages("devtools")
library(devtools)

# Step 2: Install MetaboAnalystR with documentation
devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_vignettes = TRUE, build_manual =T)
